import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

import { Arima } from 'next/font/google'
import { css } from '../../styled-system/css'
import { Input } from "@/components/Input/Input";
import { flex } from "../../styled-system/patterns";

import { RiLoginBoxLine } from "react-icons/ri";
import { button } from "@/components/Button/button.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const arima = Arima({
  weight: ['400', '700'],
  subsets: ['latin'],
})

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={css({ bg: "background", h: "100vh", w: "100%", px: "4", py: "2" })}>
        <header className={css({ w: "100%", p: "2" })}>
          <div className={flex({
            justify: "space-between"
          })}>
            <h1 className={`${arima.className} ${css({ fontSize: '4xl', color: "#921A40" })}`}>
              myDictionary
            </h1>
            <nav className={css({})}>
              <ul className={flex({ align: "right" })}>
                <li>
                  <div className={css({ mr: "10" })}>
                    <Input />
                  </div>
                </li>
                <li>
                  <button className={button({ variant: "solid", size: "md" })} >
                    <div className={flex({ align: "end" })}>
                      <RiLoginBoxLine style={{ marginRight: "5px", fontSize: "20px" }} />
                      Login
                    </div>
                  </button>
                </li>
                <li></li>
              </ul>
            </nav>
          </div>
        </header>
        {children}
      </body>
    </html>
  );
}
